#!/user/bin/python

import sys
sys.path.append('~/commit-msg-files')
from rules import rules
import re
def main():
    finalLine = "# ------------------------ >8 ------------------------"
    commentSymbol = "#"
    with open(sys.argv[1], "r") as fp:
        lines = fp.readlines()

        for idx, line in enumerate(lines):
            if (line.strip() == finalLine):
                break

            if (line[0] == commentSymbol):
                continue

            if not line_valid(idx, line):
                print("Errors were encountered in your commit.")
                show_rules()
                sys.exit(1)
    sys.exit(0)

def line_valid(idx, line):
    if idx == 0:
        return re.match("^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|release)(: ).{0,49}[0-9A-z \t]$", line)
    elif idx == 1:
        return len(line.strip()) == 0
    else:
        return len(line.strip()) <= 72

def show_rules():
    print(rules)

if __name__ == "__main__":
    main()