#!/user/bin/python

import sys
sys.path.append('~/commit-msg-files')
from rules import rules
from semantic_words import semantic_words
import re
def main():
    finalLine = "# ------------------------ >8 ------------------------"
    commentSymbol = "#"
    with open(sys.argv[1], "r") as fp:
        lines = fp.readlines()

        for idx, line in enumerate(lines):
            if (line.strip() == finalLine):
                break

            if (line[0] == commentSymbol):
                continue

            if not line_valid(idx, line):                
                show_rules()
                print("\n")
                print("commit-msg: Errors were encountered in your commit. :( \n Check previous information.")                
                sys.exit(1)
                
    print("\n")
    print("commit-msg: All is okey. :) Let's push it")    
    sys.exit(0)

def line_valid(idx, line):
    if idx == 0:
        separator = "|"
        sWords = separator.join(semantic_words)
        regex = "^(" + sWords + ")(: ).{0,49}[0-9A-z \t]$"
        return re.match(regex, line)
        #return re.match("^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|release)(: ).{0,49}[0-9A-z \t]$", line)
    elif idx == 1:
        return len(line.strip()) == 0
    else:
        return len(line.strip()) <= 72

def show_rules():
    print(rules)

if __name__ == "__main__":
    main()